
title: Sauru
description: >
Your Resume
<a href="https://www.linkedin.com/in/vishalraj1/">
  <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for" alt="LinkedIn">
</a>

<a href="mailto:rajputvishal33876@gmail.com">
  <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=fon" alt="Gmail">
</a>

theme: jekyll-theme-minimal
