
title: Sauru
description: >
Your Resume

<a href="mailto:saurabh6527@gmail.com">
  <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=fon" alt="Gmail">
</a>

theme: jekyll-theme-minimal
